install: true
language: java
script:
- ./gradlew clean build 
after_success:
- test $TRAVIS_TAG != false || ./gradlew -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY artifactoryPublish
cache:
  directories:
  - $HOME/.gradle
jdk:
- oraclejdk8
env:
  global:
  - TERM=dumb
  - secure: eS+IoYKc+eNlkoaW84DVTsE3dqZxOSoijjb7pHpjMjGO42CxNfrlOBfX9mdj7HSE0LSQvcT5blIOgxg8x8SpLZkUwBMFI6KekYYIobdR+r440HrCRh5FLJ1LshHAnexiiVrgIzQ7HxcjjquU8/ZzkV2NdIrxa2pRtisSQKiqSb/sDsxoyVkfn7mc58wQSAo55S2pUnncFDT/22FF7GJVEnF/ZRTULMf3Nx/rltHcPTLRf/xS94q62lCp4H/Aa2TJj/d0L8mCRgdOl7nTtUw7YF/fMJbnS3gPoZ1aclLRALtP5rp3YuNrGYPzmZIckDddZdHdKhesNURTqZ5HdtqGBifEjoUUnlooXrauanqVGeD5YdXgctFd9KahDw3PJZDPmaGs3lirPGabCh1gihWxLrfblxK2FDyMFVoQ8KC304dJ5bby84/JukU33pgOCr8SWEEc2vxBWDelcQndpZhee7bIgrgPhsFM6O3gOUwBTLPDUY0vAQXWW+yqXBP2r4MkA6xatZTho78mtxOidMPSezh4lGMxIVSA/WoVtIvjMcuHKZuzBZ8ldsCUGgyd8jmVWd3s+ewThfYPP7UtM2s12x7D6WZOH3HHC+/05D+9HcJSMzy2rs9+5NWqGrLXdztB7SCjPkLvzn63a2bH5hginbW/+svkb2BpmgpyBupLvYs=
  - secure: IMz5IaFzlcP5WqC5QJD962bU4tlovskAW4fY3ML681W6ZOd1McuPleUdRDtKNpZBM3X4XfTkNVooMtG9wmNsSAIPWIdKtlSvB2hXk6nVQVFLcaz1t43b/i5/qcfKMlZ2SuXB1wbtKkrxP6uPTRGhDVKLOAfONjpkGAtRbmEQyKSyBUX6NQZjdO+EU1jCe0oekMeANZboCduKaw7XOcNKWNgNBs6OP0WBWGm0A2NDZUGSwuQep9/aVGloiRo1n2FwjujoP2lKegDVPagBKPi8Cthjg9ofpo7xQywK7+lgxeLeDlARm3VUjTPGRVtl+uiZhl2H7A6TUnrvG0fmy3eQLP0hIG5OzlRHLmF0rjHri/CsohLNOO+ELEqd+WqufgpmNoer+LU0dBFNKfUYXTx8P4/dnGtK8jvE3dzv5FBOjNCu3ZCs869cdvDn7Jx+LgaknzCQ6+BanIj9nrA2aOFkyLIfrhEmQQPINEyXCHybo+31147jYPwKcQjeb3gJ8CQxiUsAYR/9m66LsgVm1KhUMaVW2cWnd6AylGOPWRh7Tsab5PIUf58x4Y5toBM5cXB/D6YAUbrUXatNahSTJ6aTbgADtMq7Tjih23g/er0qkPSD0jw7wNQf5RPE6x6nmCAOC5GQ1Qe9Wu7GEUlcZYQC+CW3JM1HPvHnwDH5IUzxjBY=
sudo: false
